// Demo data used when Sanity is not configured or has no content

export const demoLocations = [
  // Macro locations
  { _id: '1', name: 'Lisbon', slug: { current: 'lisbon' }, region: 'Lisbon', locationType: 'macro', parentLocation: null, intro: 'The Portuguese capital combines centuries of architectural heritage with a dynamic contemporary scene. Lisbon offers some of Europe\'s most compelling urban living, from the historic Alfama to the riverside Ribeira moderna.' },
  { _id: '2', name: 'Porto', slug: { current: 'porto' }, region: 'Porto', locationType: 'macro', parentLocation: null, intro: 'Porto\'s renewed confidence as a European cultural capital has catalysed a generation of exceptional new residential projects. The city blends granite severity with warm hospitality.' },
  { _id: '3', name: 'Cascais', slug: { current: 'cascais' }, region: 'Cascais', locationType: 'macro', parentLocation: null, intro: 'Cascais has long been the preferred address for affluent Lisboetas and international buyers seeking Atlantic-facing living within reach of the capital.' },
  { _id: '4', name: 'Algarve', slug: { current: 'algarve' }, region: 'Algarve', locationType: 'macro', parentLocation: null, intro: 'The Algarve\'s international appeal has been consistently underwritten by exceptional climate, infrastructure, and the finest golf courses in Europe.' },
  { _id: '5', name: 'Comporta', slug: { current: 'comporta' }, region: 'Comporta', locationType: 'macro', parentLocation: null, intro: 'Comporta has emerged as Portugal\'s most coveted new destination — a protected coastal enclave combining extraordinary natural beauty with low-density, design-led development.' },
  { _id: '6', name: 'Gaia', slug: { current: 'gaia' }, region: 'Gaia', locationType: 'macro', parentLocation: null, intro: 'Across the Douro from Porto, Gaia offers exceptional river and city views alongside a compelling pipeline of high-specification residential projects.' },
  { _id: '7', name: 'Silver Coast', slug: { current: 'silver-coast' }, region: 'Silver Coast', locationType: 'macro', parentLocation: null, intro: 'The Silver Coast — spanning the Atlantic-facing stretch from Óbidos to Ericeira, through Peniche and Nazaré — remains one of Portugal\'s most undervalued residential propositions for international buyers seeking authenticity at scale.' },
  { _id: '8', name: 'Madeira', slug: { current: 'madeira' }, region: 'Madeira', locationType: 'macro', parentLocation: null, intro: 'Madeira\'s combination of subtropical climate, favourable tax environment, and a new generation of high-specification residential supply has brought the island into serious consideration for international buyers.' },
  // Neighbourhood locations — Lisbon
  { _id: 'n1', name: 'Príncipe Real', slug: { current: 'principe-real' }, region: 'Lisbon', locationType: 'neighbourhood', parentLocation: { name: 'Lisbon', slug: { current: 'lisbon' } }, intro: 'Príncipe Real is Lisbon\'s most curated address — a hillside quarter of 19th-century palaces, independent boutiques, and a distinguished residential tradition. Its relative quietude within the Lisbon luxury market makes it the neighbourhood most consistently referenced in Viriato\'s editorial work.', latitude: 38.7169, longitude: -9.1529 },
  { _id: 'n2', name: 'Chiado', slug: { current: 'chiado' }, region: 'Lisbon', locationType: 'neighbourhood', parentLocation: { name: 'Lisbon', slug: { current: 'lisbon' } }, intro: 'Chiado occupies the cultural and commercial heart of central Lisbon. Its cobbled slopes, literary heritage, and concentration of high-end retail have made it the first neighbourhood most international buyers visit — and one of the most competitive for new residential supply.', latitude: 38.7105, longitude: -9.1424 },
  { _id: 'n3', name: 'Parque das Nações', slug: { current: 'parque-das-nacoes' }, region: 'Lisbon', locationType: 'neighbourhood', parentLocation: { name: 'Lisbon', slug: { current: 'lisbon' } }, intro: 'Built on the site of Expo \'98, Parque das Nações represents Lisbon\'s most coherent example of contemporary urban planning. Wide boulevards, riverside promenades, and consistently high-specification residential stock attract a younger, internationally mobile buyer profile.', latitude: 38.7583, longitude: -9.0933 },
  // Neighbourhood locations — Porto
  { _id: 'n4', name: 'Foz do Douro', slug: { current: 'foz-do-douro' }, region: 'Porto', locationType: 'neighbourhood', parentLocation: { name: 'Porto', slug: { current: 'porto' } }, intro: 'Foz do Douro sits where the River Douro meets the Atlantic — Porto\'s most prestigious residential address for over a century. Its combination of granite villas, ocean-facing apartments, and proximity to the city centre makes it the benchmark neighbourhood for premium Porto property.', latitude: 41.1496, longitude: -8.6726 },
  // Sub-region + nested neighbourhood — Algarve
  { _id: 'n5', name: 'Golden Triangle', slug: { current: 'golden-triangle' }, region: 'Algarve', locationType: 'sub-region', parentLocation: { name: 'Algarve', slug: { current: 'algarve' } }, intro: 'The Golden Triangle — comprising Vale do Lobo, Quinta do Lago, and Vilamoura — is the Algarve\'s most established premium resort zone. Two decades of sustained international capital have created an ecosystem of golf courses, branded residences, and villa communities with proven rental and capital performance.', latitude: 37.0635, longitude: -8.0800 },
  { _id: 'n6', name: 'Vale do Lobo', slug: { current: 'vale-do-lobo' }, region: 'Algarve', locationType: 'neighbourhood', parentLocation: { name: 'Golden Triangle', slug: { current: 'golden-triangle' } }, intro: 'Vale do Lobo is the Algarve\'s most recognised resort address — a private condominium of international standing with two championship golf courses, Atlantic clifftop villas, and a resident community that returns year after year.', latitude: 37.0543, longitude: -8.0622 },
]

export const demoDevelopments = [
  {
    _id: 'd1',
    name: 'Encosta do Bairro',
    slug: { current: 'encosta-do-bairro' },
    status: 'Under Construction',
    type: 'Apartments',
    priceDisplay: 'From €750k',
    isFeatured: true,
    lifestyleTags: ['City Centre', 'Historic Quarter'],
    editorialThesis: 'Positioned on the upper slopes of Príncipe Real, Encosta do Bairro reinterprets the traditional Lisbon apartment block through a contemporary lens — preserving the neighbourhood\'s intimate scale while delivering specifications that meet the expectations of the most discerning buyer.',
    primaryCta: 'Register Interest',
    location: { name: 'Lisbon', slug: { current: 'lisbon' } },
    developer: { name: 'Savills Development', isViriatoClient: true },
    keyFacts: [
      { label: 'Units', value: '24 apartments' },
      { label: 'Typologies', value: 'T1 to T4' },
      { label: 'Completion', value: 'Q4 2026' },
      { label: 'Parking', value: 'Underground, 2 per unit' },
    ],
    typologyNote: 'A limited collection of 24 apartments from T1 to T4 penthouses. Three units remaining.',
    whyStandsOut: null,
    areaGuide: null,
    gallery: [],
    relatedDevelopments: [],
    relatedArticles: [],
    publishedAt: '2024-03-01',
  },
  {
    _id: 'd2',
    name: 'Quinta da Comporta',
    slug: { current: 'quinta-da-comporta' },
    status: 'Off-plan',
    type: 'Villas',
    priceDisplay: 'From €2M',
    isFeatured: true,
    lifestyleTags: ['Beachfront', 'Countryside', 'Spa & Wellness'],
    editorialThesis: 'An extraordinary collection of 12 private villas set within a 40-hectare nature reserve in the heart of Comporta. Each residence has been designed by Aires Mateus to sit lightly within the landscape — a synthesis of restraint, craft, and ecological sensitivity.',
    primaryCta: 'Download Investment Pack',
    location: { name: 'Comporta', slug: { current: 'comporta' } },
    developer: { name: 'Companhia das Lezírias', isViriatoClient: false },
    keyFacts: [
      { label: 'Units', value: '12 villas' },
      { label: 'Plot sizes', value: '2,000–4,500 m²' },
      { label: 'Completion', value: 'Q2 2027' },
      { label: 'Architect', value: 'Aires Mateus' },
    ],
    typologyNote: '12 villas in three configurations: Pinus (3 bed), Sobreiro (4 bed), and Maré (5 bed with pool house).',
    whyStandsOut: null,
    areaGuide: null,
    gallery: [],
    relatedDevelopments: [],
    relatedArticles: [],
    publishedAt: '2024-02-15',
  },
  {
    _id: 'd3',
    name: 'Foz Residence',
    slug: { current: 'foz-residence' },
    status: 'Selling Now',
    type: 'Apartments',
    priceDisplay: 'From €1M',
    isFeatured: true,
    lifestyleTags: ['Marina', 'City Centre'],
    editorialThesis: 'Foz Residence occupies a commanding position facing the Atlantic mouth of the Douro. Its 18 apartments — each with unobstructed sea or river views — represent the finest address in Porto\'s most prestigious neighbourhood.',
    primaryCta: 'Schedule Consultation',
    location: { name: 'Porto', slug: { current: 'porto' } },
    developer: { name: 'ARX Portugal', isViriatoClient: true },
    keyFacts: [
      { label: 'Units', value: '18 apartments' },
      { label: 'Typologies', value: 'T2 to T4 + Penthouse' },
      { label: 'Status', value: 'Ready to move in' },
      { label: 'Concierge', value: 'Full service' },
    ],
    typologyNote: '18 apartments across 9 floors. Penthouse units with private rooftop terraces available.',
    whyStandsOut: null,
    areaGuide: null,
    gallery: [],
    relatedDevelopments: [],
    relatedArticles: [],
    publishedAt: '2024-01-20',
  },
  {
    _id: 'd4',
    name: 'Cascais Marina Residences',
    slug: { current: 'cascais-marina-residences' },
    status: 'Under Construction',
    type: 'Apartments',
    priceDisplay: 'From €850k',
    isFeatured: false,
    lifestyleTags: ['Marina', 'Golf', 'Beachfront'],
    editorialThesis: 'A carefully considered development of 32 apartments directly overlooking Cascais Marina. The project brings a new level of specification to Portugal\'s most established resort town.',
    primaryCta: 'Request Brochure',
    location: { name: 'Cascais', slug: { current: 'cascais' } },
    developer: { name: 'Vanguard Properties', isViriatoClient: false },
    keyFacts: [
      { label: 'Units', value: '32 apartments' },
      { label: 'Typologies', value: 'T1 to T3' },
      { label: 'Completion', value: 'Q1 2026' },
    ],
    typologyNote: '32 apartments with marina or garden views.',
    whyStandsOut: null,
    areaGuide: null,
    gallery: [],
    relatedDevelopments: [],
    relatedArticles: [],
    publishedAt: '2024-01-10',
  },
  {
    _id: 'd5',
    name: 'Vale Verde Algarve',
    slug: { current: 'vale-verde-algarve' },
    status: 'Off-plan',
    type: 'Villas',
    priceDisplay: 'From €1.5M',
    isFeatured: true,
    lifestyleTags: ['Golf', 'Countryside', 'Investment-grade'],
    editorialThesis: 'Set within the Golden Triangle, Vale Verde is a community of 20 four and five-bedroom villas designed around a private 9-hole golf course. The architecture is respectful of the Algarvian vernacular while meeting contemporary expectations.',
    primaryCta: 'Register Interest',
    location: { name: 'Algarve', slug: { current: 'algarve' } },
    developer: { name: 'Quinta Real', isViriatoClient: true },
    keyFacts: [
      { label: 'Units', value: '20 villas' },
      { label: 'Typologies', value: '4 and 5 bed' },
      { label: 'Completion', value: 'Q3 2026' },
      { label: 'Golf', value: 'Private 9-hole course' },
    ],
    typologyNote: '20 villas in two configurations. Phase 1 of 12 villas currently available.',
    whyStandsOut: null,
    areaGuide: null,
    gallery: [],
    relatedDevelopments: [],
    relatedArticles: [],
    publishedAt: '2024-03-10',
  },
  {
    _id: 'd6',
    name: 'Douro View Gaia',
    slug: { current: 'douro-view-gaia' },
    status: 'Selling Now',
    type: 'Apartments',
    priceDisplay: 'From €500k',
    isFeatured: false,
    lifestyleTags: ['City Centre', 'Investment-grade'],
    editorialThesis: 'Douro View Gaia offers some of the most compelling river panoramas available in the greater Porto market. Its 45 apartments span 14 floors of a newly completed tower in central Vila Nova de Gaia.',
    primaryCta: 'Speak with an Advisor',
    location: { name: 'Gaia', slug: { current: 'gaia' } },
    developer: { name: 'Predibisa', isViriatoClient: false },
    keyFacts: [
      { label: 'Units', value: '45 apartments' },
      { label: 'Typologies', value: 'T0 to T3' },
      { label: 'Status', value: 'Immediate delivery' },
    ],
    typologyNote: 'Studios to 3-bedroom apartments, all with river or city views.',
    whyStandsOut: null,
    areaGuide: null,
    gallery: [],
    relatedDevelopments: [],
    relatedArticles: [],
    publishedAt: '2023-12-01',
  },
]

export const demoArticles = [
  {
    _id: 'a1',
    title: 'Why Comporta Remains Portugal\'s Most Carefully Protected Coastline',
    slug: { current: 'why-comporta-remains-portugals-most-protected-coastline' },
    category: 'area-guides',
    excerpt: 'Three decades of deliberate restraint have preserved what could easily have become another overdeveloped Atlantic resort. We examine how Comporta\'s unusual ownership structure has shaped a destination unlike any other in Portugal.',
    publishedAt: '2024-03-05',
    linkedLocation: { name: 'Comporta', slug: { current: 'comporta' } },
  },
  {
    _id: 'a2',
    title: 'The Golden Triangle: An Investment Landscape After Two Decades of Demand',
    slug: { current: 'golden-triangle-investment-landscape' },
    category: 'investment',
    excerpt: 'The Algarve\'s premium triangle — Vale do Lobo, Quinta do Lago, and Vilamoura — has absorbed consistent international capital for twenty years. What does this tell us about resilience, and where does value now sit?',
    publishedAt: '2024-02-28',
    linkedLocation: { name: 'Golden Triangle', slug: { current: 'golden-triangle' } },
  },
  {
    _id: 'a3',
    title: 'Porto\'s Foz District: The City\'s Most Coveted Address Explained',
    slug: { current: 'porto-foz-district-guide' },
    category: 'area-guides',
    excerpt: 'Foz do Douro has long been Porto\'s answer to the premium residential question. We map the neighbourhood, explain its appeal, and identify where new supply is emerging.',
    publishedAt: '2024-02-14',
    linkedLocation: { name: 'Foz do Douro', slug: { current: 'foz-do-douro' } },
  },
  {
    _id: 'a4',
    title: 'What Branded Residences Mean for Portugal\'s New Development Market',
    slug: { current: 'branded-residences-portugal-market' },
    category: 'branded-residences',
    excerpt: 'The arrival of international hotel brands as residential partners has changed the conversation around premium property in Lisbon and the Algarve. We assess the opportunity and the caveats.',
    publishedAt: '2024-01-30',
    linkedLocation: { name: 'Lisbon', slug: { current: 'lisbon' } },
  },
  {
    _id: 'a5',
    title: 'Architecture as Editorial: How the Best Portuguese Developers Are Commissioning Differently',
    slug: { current: 'architecture-as-editorial-portugal-developers' },
    category: 'architecture',
    excerpt: 'A new generation of development briefs in Portugal is placing architectural authorship at the centre of the value proposition. We speak to architects and clients about what this means in practice.',
    publishedAt: '2024-01-15',
    linkedLocation: { name: 'Lisbon', slug: { current: 'lisbon' } },
  },
  {
    _id: 'a6',
    title: 'The Lisbon Second-Home Narrative: Between Residency and Investment',
    slug: { current: 'lisbon-second-home-narrative' },
    category: 'second-home',
    excerpt: 'International buyers approaching Lisbon as a second-home market increasingly occupy a middle ground between pure investment and lifestyle acquisition. We examine what this means for product design and pricing.',
    publishedAt: '2024-01-01',
    linkedLocation: { name: 'Lisbon', slug: { current: 'lisbon' } },
  },
  {
    _id: 'a7',
    title: 'Buying Property in Portugal: A Practical Guide for International Buyers',
    slug: { current: 'buying-property-in-portugal-guide' },
    category: 'buyer-guides',
    isPillar: true,
    excerpt: 'Everything international buyers need to understand before purchasing residential property in Portugal — from the legal process and purchase costs to financing, timelines, and common pitfalls.',
    publishedAt: '2024-03-15',
    linkedLocation: null,
  },
  {
    _id: 'a8',
    title: 'Portugal Tax Incentives for Property Buyers: NHR, IFICI, and the New Regimes',
    slug: { current: 'portugal-tax-incentives-property-buyers' },
    category: 'buyer-guides',
    isPillar: true,
    excerpt: 'A clear-eyed editorial overview of the tax frameworks available to international property buyers in Portugal — including the current status of NHR, the IFICI regime, and the D7 residency route.',
    publishedAt: '2024-03-10',
    linkedLocation: null,
  },
  {
    _id: 'a9',
    title: 'Where to Buy in Portugal: A Location Intelligence Overview',
    slug: { current: 'where-to-buy-property-portugal' },
    category: 'buyer-guides',
    isPillar: true,
    excerpt: 'An editorial overview of Portugal\'s principal macro-locations for new residential development — from Lisbon and Porto to the Algarve, Comporta, Cascais, and the emerging Silver Coast.',
    publishedAt: '2024-03-01',
    linkedLocation: null,
  },
]

export const demoLifestyles = [
  {
    _id: 'ls1',
    tag: 'Golf',
    slug: { current: 'golf' },
    intro: {
      en: "Golf property in Portugal occupies a distinct position in the premium residential market. The country's courses — concentrated in the Algarve but increasingly present across the Lisbon peninsula and the Silver Coast — have created an ecosystem of resort communities, branded residences, and private villas that consistently attract serious international capital. Portugal has twelve of the top one hundred golf courses in Europe, and the lifestyle that surrounds them is one of its most bankable residential propositions.",
      pt: 'O imobiliário de golfe em Portugal ocupa uma posição distinta no mercado residencial premium. Os campos do país — concentrados no Algarve, mas cada vez mais presentes na Península de Setúbal e na Costa de Prata — criaram um ecossistema de comunidades resort e residências de marca que atrai capital internacional sério de forma consistente.',
    },
    seoTitle: 'Golf Property in Portugal — Portugal Developments Review',
    seoDescription: "Curated golf-adjacent residential developments across Portugal. Editorially selected for location, developer track record, and specification integrity.",
    noindex: false,
  },
  {
    _id: 'ls2',
    tag: 'Beachfront',
    slug: { current: 'beachfront' },
    intro: {
      en: "Beachfront property in Portugal ranges from the protected Atlantic coastline of Comporta — where low-density planning restrictions have preserved some of Europe's most extraordinary natural landscapes — to the resort-oriented frontline developments of the Algarve. The defining characteristic of the best beachfront proposition in Portugal is scarcity: genuine direct-access development opportunities are rare and, when they emerge, command sustained capital appreciation over time.",
      pt: 'O imobiliário de frente de praia em Portugal vai desde a costa atlântica protegida da Comporta — onde as restrições de planeamento preservaram algumas das paisagens naturais mais extraordinárias da Europa — até aos projetos frontline do Algarve. A característica definidora da melhor oferta beira-mar em Portugal é a escassez.',
    },
    seoTitle: 'Beachfront Property in Portugal — Portugal Developments Review',
    seoDescription: 'Curated beachfront residential developments in Portugal — Comporta, Algarve, and the Atlantic coast. Rare direct-access opportunities, editorially selected.',
    noindex: false,
  },
  {
    _id: 'ls3',
    tag: 'Investment-grade',
    slug: { current: 'investment-grade' },
    intro: {
      en: "Investment-grade designation on this platform indicates developments that have demonstrated, or carry credible potential to demonstrate, capital performance above the market baseline. This requires a combination of factors: a developer with a track record of delivering on projection, a location with sustained demand drivers, and product design that appeals to a rental market as well as a purchaser. Not every well-designed development is investment-grade; not every investment-grade development is the finest design on the market.",
      pt: 'A designação de grau de investimento nesta plataforma indica projetos que demonstraram, ou têm potencial credível para demonstrar, desempenho de capital acima da linha de base do mercado. Combina historial do promotor, localização com fatores de procura sustentados e design de produto que apela ao mercado de arrendamento.',
    },
    seoTitle: 'Investment-Grade Property in Portugal — Portugal Developments Review',
    seoDescription: 'Curated investment-grade developments across Portugal. Selected for capital performance potential, developer track record, and location fundamentals.',
    noindex: false,
  },
]

export const categoryLabels: Record<string, string> = {
  'architecture': 'Architecture',
  'area-guides': 'Area Guides',
  'branded-residences': 'Branded Residences',
  'market-intelligence': 'Market Intelligence',
  'second-home': 'Second-Home Narratives',
  'investment': 'Investment Explainers',
  'buyer-guides': 'Buyer Guides',
}

export const demoJournalCategories = [
  {
    slug: 'architecture',
    title: { en: 'Architecture', pt: 'Arquitetura' },
    intro: {
      en: "Portugal's most considered new developments begin with architecture. This section examines how leading architects are approaching residential briefs — from material selection and spatial organisation to the balance between typological tradition and contemporary expression. Our architecture coverage focuses on authorship, coherence, and the relationship between a project's stated proposition and its physical realisation.",
      pt: 'Os projetos residenciais mais considerados de Portugal começam com a arquitetura. Esta secção examina como os principais arquitetos abordam os programas residenciais — desde a seleção de materiais e a organização espacial ao equilíbrio entre a tradição tipológica e a expressão contemporânea.',
    },
    seoTitle: 'Architecture — Journal | Portugal Developments Review',
    seoDescription: 'Editorial analysis of architectural design in Portugal\'s premium new residential developments. Authorship, coherence, and the built proposition.',
  },
  {
    slug: 'area-guides',
    title: { en: 'Area Guides', pt: 'Guias de Área' },
    intro: {
      en: 'Understanding a location is the first step in understanding any development within it. Our area guides examine Portugal\'s key residential markets through the lens of urban character, infrastructure, and buyer demand — covering Lisbon\'s most coveted quartiers to the Atlantic-facing communities of the Algarve. Each guide is written to help serious buyers build a grounded picture of a location.',
      pt: 'Compreender uma localização é o primeiro passo para avaliar qualquer projeto nela inserido. Os nossos guias de área examinam os principais mercados residenciais de Portugal — desde os bairros mais cobiçados de Lisboa às comunidades atlânticas do Algarve.',
    },
    seoTitle: 'Area Guides — Journal | Portugal Developments Review',
    seoDescription: 'Editorial guides to Portugal\'s key residential locations — Lisbon, Porto, Algarve, Comporta, Cascais, and beyond.',
  },
  {
    slug: 'branded-residences',
    title: { en: 'Branded Residences', pt: 'Residências de Marca' },
    intro: {
      en: 'The arrival of international hospitality brands as residential partners has transformed the premium development landscape across Lisbon and the Algarve. Branded residences promise management infrastructure, brand premium, and rental yield — but the reality varies considerably by operator and project. Our coverage examines each partnership on its own terms.',
      pt: 'A chegada de marcas hoteleiras internacionais como parceiras residenciais transformou o panorama dos projetos premium em Lisboa e no Algarve. As residências de marca prometem infraestrutura de gestão, premium de marca e rendimento de arrendamento — mas a realidade varia consideravelmente.',
    },
    seoTitle: 'Branded Residences — Journal | Portugal Developments Review',
    seoDescription: 'Editorial analysis of branded residence developments in Portugal — hotel-branded property in Lisbon, the Algarve, and beyond.',
  },
  {
    slug: 'market-intelligence',
    title: { en: 'Market Intelligence', pt: 'Informação de Mercado' },
    intro: {
      en: 'Periodic editorial notes on the Portuguese new-development market — pricing context, pipeline observations, and PDR\'s forward view. These notes are structured editorial observations from a team with consistent access to active projects, developer briefings, and buyer behaviour across Portugal\'s principal residential markets. Published at intervals when the market warrants commentary.',
      pt: 'Notas editoriais periódicas sobre o mercado de novos projetos em Portugal — contexto de preços, observações sobre a oferta e a perspetiva da PDR. Publicadas quando o mercado justifica comentário editorial.',
    },
    seoTitle: 'Market Intelligence — Journal | Portugal Developments Review',
    seoDescription: 'Periodic editorial notes on Portugal\'s new residential development market — pricing, pipeline, and PDR\'s forward view.',
  },
  {
    slug: 'second-home',
    title: { en: 'Second-Home Narratives', pt: 'Segunda Residência' },
    intro: {
      en: 'The decision to purchase a second home in Portugal occupies a different register from a pure investment calculation. Lifestyle, access, community, and emotional alignment all carry weight alongside yield and capital performance. Our second-home coverage explores how international buyers are approaching Portugal as a destination for extended stays, and what that means for how they select locations and developments.',
      pt: 'A decisão de adquirir uma segunda habitação em Portugal situa-se num registo diferente de um cálculo puramente de investimento. Estilo de vida, acesso, comunidade e alinhamento emocional têm peso, a par com rendimento e desempenho de capital.',
    },
    seoTitle: 'Second-Home Narratives — Journal | Portugal Developments Review',
    seoDescription: 'Editorial perspectives on buying a second home in Portugal — lifestyle, location, and the international buyer\'s decision.',
  },
  {
    slug: 'investment',
    title: { en: 'Investment Explainers', pt: 'Investimento' },
    intro: {
      en: "Portugal's new development market has demonstrated consistent appeal to capital-led buyers across multiple economic cycles. Our investment coverage provides structured context — examining capital appreciation trends, rental yield profiles, and the macroeconomic factors that underwrite demand across specific markets. The aim is not to predict outcomes, but to give serious buyers the framework to ask better questions.",
      pt: 'O mercado de novos projetos em Portugal demonstrou um apelo consistente a compradores orientados para o capital em múltiplos ciclos económicos. A nossa cobertura de investimento fornece contexto estruturado — examinando tendências de valorização e perfis de rendimento de arrendamento.',
    },
    seoTitle: 'Investment Explainers — Journal | Portugal Developments Review',
    seoDescription: 'Editorial analysis of Portugal property investment — capital appreciation, rental yields, and market context across key locations.',
  },
  {
    slug: 'buyer-guides',
    title: { en: 'Buyer Guides', pt: 'Guias de Compra' },
    intro: {
      en: 'Purchasing property in a foreign market requires a different kind of preparation. Our buyer guides address the procedural, legal, and financial realities of acquiring new-build property in Portugal — from the purchase process and transaction costs to financing structures, tax considerations, and the practical timeline from offer to keys. Written for the internationally mobile buyer who wants editorial clarity.',
      pt: 'Adquirir um imóvel num mercado estrangeiro exige uma preparação diferente. Os nossos guias de compra abordam as realidades processuais, legais e financeiras da aquisição de imóveis novos em Portugal — desde o processo de compra e custos de transação até às estruturas de financiamento.',
    },
    seoTitle: 'Buyer Guides — Journal | Portugal Developments Review',
    seoDescription: 'Practical guides to buying property in Portugal for international buyers — legal process, costs, financing, and timelines explained.',
  },
]
