// Demo data used when Sanity is not configured or has no content

export const demoLocations = [
  { _id: '1', name: 'Lisbon', slug: { current: 'lisbon' }, region: 'Lisbon', intro: 'The Portuguese capital combines centuries of architectural heritage with a dynamic contemporary scene. Lisbon offers some of Europe\'s most compelling urban living, from the historic Alfama to the riverside Ribeira moderna.' },
  { _id: '2', name: 'Porto', slug: { current: 'porto' }, region: 'Porto', intro: 'Porto\'s renewed confidence as a European cultural capital has catalysed a generation of exceptional new residential projects. The city blends granite severity with warm hospitality.' },
  { _id: '3', name: 'Cascais', slug: { current: 'cascais' }, region: 'Cascais', intro: 'Cascais has long been the preferred address for affluent Lisboetas and international buyers seeking Atlantic-facing living within reach of the capital.' },
  { _id: '4', name: 'Algarve', slug: { current: 'algarve' }, region: 'Algarve', intro: 'The Algarve\'s international appeal has been consistently underwritten by exceptional climate, infrastructure, and the finest golf courses in Europe.' },
  { _id: '5', name: 'Comporta', slug: { current: 'comporta' }, region: 'Comporta', intro: 'Comporta has emerged as Portugal\'s most coveted new destination — a protected coastal enclave combining extraordinary natural beauty with low-density, design-led development.' },
  { _id: '6', name: 'Gaia', slug: { current: 'gaia' }, region: 'Gaia', intro: 'Across the Douro from Porto, Gaia offers exceptional river and city views alongside a compelling pipeline of high-specification residential projects.' },
]

export const demoDevelopments = [
  {
    _id: 'd1',
    name: 'Encosta do Bairro',
    slug: { current: 'encosta-do-bairro' },
    status: 'Under Construction',
    type: 'Apartments',
    priceDisplay: 'From €750k',
    isFeatured: true,
    lifestyleTags: ['City Centre', 'Historic Quarter'],
    editorialThesis: 'Positioned on the upper slopes of Príncipe Real, Encosta do Bairro reinterprets the traditional Lisbon apartment block through a contemporary lens — preserving the neighbourhood\'s intimate scale while delivering specifications that meet the expectations of the most discerning buyer.',
    primaryCta: 'Register Interest',
    location: { name: 'Lisbon', slug: { current: 'lisbon' } },
    developer: { name: 'Savills Development', isViriatoClient: true },
    keyFacts: [
      { label: 'Units', value: '24 apartments' },
      { label: 'Typologies', value: 'T1 to T4' },
      { label: 'Completion', value: 'Q4 2026' },
      { label: 'Parking', value: 'Underground, 2 per unit' },
    ],
    typologyNote: 'A limited collection of 24 apartments from T1 to T4 penthouses. Three units remaining.',
    whyStandsOut: null,
    areaGuide: null,
    gallery: [],
    relatedDevelopments: [],
    relatedArticles: [],
    publishedAt: '2024-03-01',
  },
  {
    _id: 'd2',
    name: 'Quinta da Comporta',
    slug: { current: 'quinta-da-comporta' },
    status: 'Off-plan',
    type: 'Villas',
    priceDisplay: 'From €2M',
    isFeatured: true,
    lifestyleTags: ['Beachfront', 'Countryside', 'Spa & Wellness'],
    editorialThesis: 'An extraordinary collection of 12 private villas set within a 40-hectare nature reserve in the heart of Comporta. Each residence has been designed by Aires Mateus to sit lightly within the landscape — a synthesis of restraint, craft, and ecological sensitivity.',
    primaryCta: 'Download Investment Pack',
    location: { name: 'Comporta', slug: { current: 'comporta' } },
    developer: { name: 'Companhia das Lezírias', isViriatoClient: false },
    keyFacts: [
      { label: 'Units', value: '12 villas' },
      { label: 'Plot sizes', value: '2,000–4,500 m²' },
      { label: 'Completion', value: 'Q2 2027' },
      { label: 'Architect', value: 'Aires Mateus' },
    ],
    typologyNote: '12 villas in three configurations: Pinus (3 bed), Sobreiro (4 bed), and Maré (5 bed with pool house).',
    whyStandsOut: null,
    areaGuide: null,
    gallery: [],
    relatedDevelopments: [],
    relatedArticles: [],
    publishedAt: '2024-02-15',
  },
  {
    _id: 'd3',
    name: 'Foz Residence',
    slug: { current: 'foz-residence' },
    status: 'Selling Now',
    type: 'Apartments',
    priceDisplay: 'From €1M',
    isFeatured: true,
    lifestyleTags: ['Marina', 'City Centre'],
    editorialThesis: 'Foz Residence occupies a commanding position facing the Atlantic mouth of the Douro. Its 18 apartments — each with unobstructed sea or river views — represent the finest address in Porto\'s most prestigious neighbourhood.',
    primaryCta: 'Schedule Consultation',
    location: { name: 'Porto', slug: { current: 'porto' } },
    developer: { name: 'ARX Portugal', isViriatoClient: true },
    keyFacts: [
      { label: 'Units', value: '18 apartments' },
      { label: 'Typologies', value: 'T2 to T4 + Penthouse' },
      { label: 'Status', value: 'Ready to move in' },
      { label: 'Concierge', value: 'Full service' },
    ],
    typologyNote: '18 apartments across 9 floors. Penthouse units with private rooftop terraces available.',
    whyStandsOut: null,
    areaGuide: null,
    gallery: [],
    relatedDevelopments: [],
    relatedArticles: [],
    publishedAt: '2024-01-20',
  },
  {
    _id: 'd4',
    name: 'Cascais Marina Residences',
    slug: { current: 'cascais-marina-residences' },
    status: 'Under Construction',
    type: 'Apartments',
    priceDisplay: 'From €850k',
    isFeatured: false,
    lifestyleTags: ['Marina', 'Golf', 'Beachfront'],
    editorialThesis: 'A carefully considered development of 32 apartments directly overlooking Cascais Marina. The project brings a new level of specification to Portugal\'s most established resort town.',
    primaryCta: 'Request Brochure',
    location: { name: 'Cascais', slug: { current: 'cascais' } },
    developer: { name: 'Vanguard Properties', isViriatoClient: false },
    keyFacts: [
      { label: 'Units', value: '32 apartments' },
      { label: 'Typologies', value: 'T1 to T3' },
      { label: 'Completion', value: 'Q1 2026' },
    ],
    typologyNote: '32 apartments with marina or garden views.',
    whyStandsOut: null,
    areaGuide: null,
    gallery: [],
    relatedDevelopments: [],
    relatedArticles: [],
    publishedAt: '2024-01-10',
  },
  {
    _id: 'd5',
    name: 'Vale Verde Algarve',
    slug: { current: 'vale-verde-algarve' },
    status: 'Off-plan',
    type: 'Villas',
    priceDisplay: 'From €1.5M',
    isFeatured: true,
    lifestyleTags: ['Golf', 'Countryside', 'Investment-grade'],
    editorialThesis: 'Set within the Golden Triangle, Vale Verde is a community of 20 four and five-bedroom villas designed around a private 9-hole golf course. The architecture is respectful of the Algarvian vernacular while meeting contemporary expectations.',
    primaryCta: 'Register Interest',
    location: { name: 'Algarve', slug: { current: 'algarve' } },
    developer: { name: 'Quinta Real', isViriatoClient: true },
    keyFacts: [
      { label: 'Units', value: '20 villas' },
      { label: 'Typologies', value: '4 and 5 bed' },
      { label: 'Completion', value: 'Q3 2026' },
      { label: 'Golf', value: 'Private 9-hole course' },
    ],
    typologyNote: '20 villas in two configurations. Phase 1 of 12 villas currently available.',
    whyStandsOut: null,
    areaGuide: null,
    gallery: [],
    relatedDevelopments: [],
    relatedArticles: [],
    publishedAt: '2024-03-10',
  },
  {
    _id: 'd6',
    name: 'Douro View Gaia',
    slug: { current: 'douro-view-gaia' },
    status: 'Selling Now',
    type: 'Apartments',
    priceDisplay: 'From €500k',
    isFeatured: false,
    lifestyleTags: ['City Centre', 'Investment-grade'],
    editorialThesis: 'Douro View Gaia offers some of the most compelling river panoramas available in the greater Porto market. Its 45 apartments span 14 floors of a newly completed tower in central Vila Nova de Gaia.',
    primaryCta: 'Speak with an Advisor',
    location: { name: 'Gaia', slug: { current: 'gaia' } },
    developer: { name: 'Predibisa', isViriatoClient: false },
    keyFacts: [
      { label: 'Units', value: '45 apartments' },
      { label: 'Typologies', value: 'T0 to T3' },
      { label: 'Status', value: 'Immediate delivery' },
    ],
    typologyNote: 'Studios to 3-bedroom apartments, all with river or city views.',
    whyStandsOut: null,
    areaGuide: null,
    gallery: [],
    relatedDevelopments: [],
    relatedArticles: [],
    publishedAt: '2023-12-01',
  },
]

export const demoArticles = [
  {
    _id: 'a1',
    title: 'Why Comporta Remains Portugal\'s Most Carefully Protected Coastline',
    slug: { current: 'why-comporta-remains-portugals-most-protected-coastline' },
    category: 'area-guides',
    excerpt: 'Three decades of deliberate restraint have preserved what could easily have become another overdeveloped Atlantic resort. We examine how Comporta\'s unusual ownership structure has shaped a destination unlike any other in Portugal.',
    publishedAt: '2024-03-05',
    linkedLocation: { name: 'Comporta', slug: { current: 'comporta' } },
  },
  {
    _id: 'a2',
    title: 'The Golden Triangle: An Investment Landscape After Two Decades of Demand',
    slug: { current: 'golden-triangle-investment-landscape' },
    category: 'investment',
    excerpt: 'The Algarve\'s premium triangle — Vale do Lobo, Quinta do Lago, and Vilamoura — has absorbed consistent international capital for twenty years. What does this tell us about resilience, and where does value now sit?',
    publishedAt: '2024-02-28',
    linkedLocation: { name: 'Algarve', slug: { current: 'algarve' } },
  },
  {
    _id: 'a3',
    title: 'Porto\'s Foz District: The City\'s Most Coveted Address Explained',
    slug: { current: 'porto-foz-district-guide' },
    category: 'area-guides',
    excerpt: 'Foz do Douro has long been Porto\'s answer to the premium residential question. We map the neighbourhood, explain its appeal, and identify where new supply is emerging.',
    publishedAt: '2024-02-14',
    linkedLocation: { name: 'Porto', slug: { current: 'porto' } },
  },
  {
    _id: 'a4',
    title: 'What Branded Residences Mean for Portugal\'s New Development Market',
    slug: { current: 'branded-residences-portugal-market' },
    category: 'branded-residences',
    excerpt: 'The arrival of international hotel brands as residential partners has changed the conversation around premium property in Lisbon and the Algarve. We assess the opportunity and the caveats.',
    publishedAt: '2024-01-30',
    linkedLocation: { name: 'Lisbon', slug: { current: 'lisbon' } },
  },
  {
    _id: 'a5',
    title: 'Architecture as Editorial: How the Best Portuguese Developers Are Commissioning Differently',
    slug: { current: 'architecture-as-editorial-portugal-developers' },
    category: 'architecture',
    excerpt: 'A new generation of development briefs in Portugal is placing architectural authorship at the centre of the value proposition. We speak to architects and clients about what this means in practice.',
    publishedAt: '2024-01-15',
    linkedLocation: { name: 'Lisbon', slug: { current: 'lisbon' } },
  },
  {
    _id: 'a6',
    title: 'The Lisbon Second-Home Narrative: Between Residency and Investment',
    slug: { current: 'lisbon-second-home-narrative' },
    category: 'second-home',
    excerpt: 'International buyers approaching Lisbon as a second-home market increasingly occupy a middle ground between pure investment and lifestyle acquisition. We examine what this means for product design and pricing.',
    publishedAt: '2024-01-01',
    linkedLocation: { name: 'Lisbon', slug: { current: 'lisbon' } },
  },
  {
    _id: 'a7',
    title: 'Buying Property in Portugal: A Practical Guide for International Buyers',
    slug: { current: 'buying-property-in-portugal-guide' },
    category: 'buyer-guides',
    isPillar: true,
    excerpt: 'Everything international buyers need to understand before purchasing residential property in Portugal — from the legal process and purchase costs to financing, timelines, and common pitfalls.',
    publishedAt: '2024-03-15',
    linkedLocation: null,
  },
  {
    _id: 'a8',
    title: 'Portugal Tax Incentives for Property Buyers: NHR, IFICI, and the New Regimes',
    slug: { current: 'portugal-tax-incentives-property-buyers' },
    category: 'buyer-guides',
    isPillar: true,
    excerpt: 'A clear-eyed editorial overview of the tax frameworks available to international property buyers in Portugal — including the current status of NHR, the IFICI regime, and the D7 residency route.',
    publishedAt: '2024-03-10',
    linkedLocation: null,
  },
  {
    _id: 'a9',
    title: 'Where to Buy in Portugal: A Location Intelligence Overview',
    slug: { current: 'where-to-buy-property-portugal' },
    category: 'buyer-guides',
    isPillar: true,
    excerpt: 'An editorial overview of Portugal\'s principal macro-locations for new residential development — from Lisbon and Porto to the Algarve, Comporta, Cascais, and the emerging Silver Coast.',
    publishedAt: '2024-03-01',
    linkedLocation: null,
  },
]

export const categoryLabels: Record<string, string> = {
  'architecture': 'Architecture',
  'area-guides': 'Area Guides',
  'branded-residences': 'Branded Residences',
  'new-developments': 'New Developments',
  'second-home': 'Second-Home Narratives',
  'investment': 'Investment Explainers',
  'buyer-guides': 'Buyer Guides',
}
